$$
D(p||q)=\sum_i p_i\log\frac{p_i}{q_i}
$$

In [17]:
import numpy as np

p = np.random.uniform(0.,1.,3)
q = np.random.uniform(0.,1.,3) 
r = np.random.uniform(0.,1.,3) 

p = p / np.sum(p)
q = q / np.sum(q)
r = r / np.sum(r)
print(p)
print(q)
print(r)
print()

d_pq = np.sum(p*np.log(p/q))
d_qr = np.sum(q*np.log(q/r))
d_pr = np.sum(p*np.log(p/r))
print(d_pq+d_qr-d_pr)

[0.50235313 0.21151921 0.28612766]
[0.16077333 0.29924492 0.53998174]
[0.12697161 0.42070191 0.45232648]

-0.06554312455380851
