In [1]:
import numpy as np

# t = 0
# batch_size = 4
# n_features = 3
x_0_batch = np.array(
    [[0, 1, 2], 
     [3, 4, 5], 
     [6, 7, 8], 
     [9, 0, 1]]) 

In [2]:
# t = 1
# batch_size = 4
# n_features = 3
x_1_batch = np.array(
    [[9, 8, 7], 
     [0, 0, 0], 
     [6, 5, 4], 
     [3, 2, 1]]) 

In [3]:
import tensorflow as tf
import numpy as np
tf.reset_default_graph()
tf.set_random_seed(0)
np.random.seed(0)

In [4]:
# for a time series data of batch_size = 1
# at each time t
# observation.shape = (n_inputs,)
n_inputs = 3

In [5]:
# internally current state is represented by neurons 
# n_neurons.shape = (n_neurons,)
n_neurons = 5

In [6]:
# placehoder to feed batch data of time 0
x_0 = tf.placeholder(tf.float32, [None, n_inputs])

In [7]:
# placehoder to feed batch data of time 1
x_1 = tf.placeholder(tf.float32, [None, n_inputs])

In [8]:
init_w = tf.keras.initializers.VarianceScaling(mode='fan_avg')
init_b = tf.keras.initializers.zeros()

w_x = tf.get_variable('w_x', [n_inputs, n_neurons], tf.float32, init_w)
w_y = tf.get_variable('w_y', [n_neurons,n_neurons], tf.float32, init_w)
b = tf.get_variable('b', [1, n_neurons], tf.float32, init_b)

$$
y_t = \varphi\left(y_{t-1}W_y+x_tW_x+b\right)
$$

In [9]:
y__1 = tf.constant([[0., 0., 0., 0., 0.]]) # output at t = -1
y_0 = tf.tanh(y__1@w_y+x_0@w_x+b)          # output at t = 0
y_1 = tf.tanh(y_0@w_y+x_1@w_x+b)           # output at t = 1

In [10]:
init = tf.global_variables_initializer()

In [11]:
with tf.Session() as sess:
    
    init.run()
    
    feed_dict = {x_0: x_0_batch, x_1: x_1_batch}
    y_0_val, y_1_val = sess.run([y_0, y_1], feed_dict=feed_dict)

In [12]:
print(y_0_val) # output at t = 0

[[-0.56105095  0.91834176  0.5135985  -0.6539502  -0.13548155]
 [-0.5136927   0.9940348   0.9864494  -0.9958844   0.31813723]
 [-0.4629826   0.9995796   0.9997104  -0.9999594   0.66149455]
 [ 0.81087196 -0.18508233  0.9615377  -0.9983009   0.9991952 ]]


In [13]:
print(y_1_val) # output at t = 1

[[ 0.8553927   0.96498966  0.9997008  -0.9999967   0.9578201 ]
 [ 0.22906882 -0.78643215 -0.73852944 -0.08315186  0.6745081 ]
 [ 0.75410056 -0.32146144  0.9891128  -0.9988326   0.9633329 ]
 [-0.34363183 -0.9705283   0.75431883  0.29336378  0.90682846]]
