In [1]:
import numpy as np

# t = 0
# batch_size = 4
# n_features = 3
x_0_batch = np.array(
    [[0, 1, 2], 
     [3, 4, 5], 
     [6, 7, 8], 
     [9, 0, 1]]) 

In [2]:
# t = 1
# batch_size = 4
# n_features = 3
x_1_batch = np.array(
    [[9, 8, 7], 
     [0, 0, 0], 
     [6, 5, 4], 
     [3, 2, 1]]) 

In [3]:
import tensorflow as tf
import numpy as np
tf.reset_default_graph()
tf.set_random_seed(0)
np.random.seed(0)

In [4]:
# for a time series data of batch_size = 1
# at each time t
# observation.shape = (n_inputs,)
n_inputs = 3

In [5]:
# internally current state is represented by neurons 
# n_neurons.shape = (n_neurons,)
n_neurons = 5

In [6]:
# placehoder to feed batch data of time 0
x_0 = tf.placeholder(tf.float32, [None, n_inputs])

In [7]:
# placehoder to feed batch data of time 1
x_1 = tf.placeholder(tf.float32, [None, n_inputs])

In [8]:
init_w = tf.keras.initializers.VarianceScaling(mode='fan_avg')
init_b = tf.keras.initializers.zeros()

w_x = tf.get_variable('w_x', [n_inputs, n_neurons], tf.float32, init_w)
w_y = tf.get_variable('w_y', [n_neurons,n_neurons], tf.float32, init_w)
b = tf.get_variable('b', [1, n_neurons], tf.float32, init_b)

$$
y_t = \varphi\left(y_{t-1}W_y+x_tW_x+b\right)
$$

In [9]:
y__1 = tf.constant([[0., 0., 0., 0., 0.]]) # output at t = -1
y_0 = tf.tanh(y__1@w_y+x_0@w_x+b)          # output at t = 0
y_1 = tf.tanh(y_0@w_y+x_1@w_x+b)           # output at t = 1

In [10]:
# a factory that creates copies of the cell to build the unrolled RNN
basic_cell = tf.nn.rnn_cell.BasicRNNCell(num_units=n_neurons)

# output: a Python list containing the output tensors for each time step.
# states: a tensor containing the final states of the network.
output, states = tf.nn.static_rnn(basic_cell, [x_0, x_1], dtype=tf.float32)

Instructions for updating:
This class is equivalent as tf.keras.layers.SimpleRNNCell, and will be replaced by that in Tensorflow 2.0.
Instructions for updating:
Please use `keras.layers.RNN(cell, unroll=True)`, which is equivalent to this API
Instructions for updating:
Please use `layer.add_weight` method instead.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [11]:
init = tf.global_variables_initializer()

In [12]:
with tf.Session() as sess:
    
    init.run()
    
    feed_dict = {x_0: x_0_batch, x_1: x_1_batch}
    output_val = sess.run(output, feed_dict=feed_dict)

In [13]:
# print(output.shape) # AttributeError: 'list' object has no attribute 'shape'
# print(output_val.shape) # AttributeError: 'list' object has no attribute 'shape'

In [14]:
print(output_val[0]) # output at t = 0

[[-0.816316    0.48939312 -0.31682497  0.63428956 -0.83109623]
 [-0.8589758   0.8326569   0.10448586  0.99602646 -0.93487126]
 [-0.8923153   0.9525135   0.4913596   0.99996465 -0.97573155]
 [ 0.99899584 -0.9497187   0.5536328   0.9933496   0.9990816 ]]


In [15]:
print(output_val[1]) # output at t = 1

[[ 0.86336017  0.71697336  0.86756456  0.9999967  -0.6551463 ]
 [ 0.63544226 -0.7937349  -0.264276    0.48043317 -0.29379207]
 [ 0.9292934  -0.5168714   0.76162595  0.9997505  -0.01624893]
 [ 0.58046395 -0.06621899  0.8626206   0.97334087  0.68243587]]
