In [1]:
import numpy as np

x_batch = np.array([
    # t  =  0 ,  t  =  1
    [[0, 1, 2], [9, 8, 7]], # instance 0
    [[3, 4, 5], [0, 0, 0]], # instance 1 
    [[6, 7, 8], [6, 5, 4]], # instance 2
    [[9, 0, 1], [3, 2, 1]], # instance 3
])

In [2]:
import numpy as np

x_batch = np.array([
    # t  =  0 ,  t  =  1
    [[0, 1, 2], [9, 8, 7]], # instance 0
    [[3, 4, 5], [0, 0, 0]], # instance 1 (padded with zero vectors)
    [[6, 7, 8], [6, 5, 4]], # instance 2
    [[9, 0, 1], [3, 2, 1]], # instance 3
])

seq_length_batch = np.array([2, 1, 2, 2])

In [3]:
import tensorflow as tf
import numpy as np
tf.reset_default_graph()
tf.set_random_seed(0)
np.random.seed(0)

In [4]:
# for a time series data of batch_size = 1
# at each time t
# observation.shape = (n_inputs,)
n_inputs = 3

In [5]:
# internally current state is represented by neurons 
# n_neurons.shape = (n_neurons,)
n_neurons = 5

In [6]:
# n_steps = 2
# x = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
# basic_cell = tf.nn.rnn_cell.BasicRNNCell(num_units=n_neurons)
# output, states = tf.nn.dynamic_rnn(basic_cell, x, dtype=tf.float32)

In [7]:
n_steps = 2
x = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
seq_length = tf.placeholder(tf.int32, [None])
basic_cell = tf.nn.rnn_cell.BasicRNNCell(num_units=n_neurons)
output, states = tf.nn.dynamic_rnn(basic_cell, x, dtype=tf.float32,
                                   sequence_length=seq_length)

Instructions for updating:
This class is equivalent as tf.keras.layers.SimpleRNNCell, and will be replaced by that in Tensorflow 2.0.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
Instructions for updating:
Please use `layer.add_weight` method instead.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [8]:
init = tf.global_variables_initializer()

In [9]:
with tf.Session() as sess:
    
    init.run()
    
    feed_dict = {x: x_batch}
    output_val = sess.run(output, feed_dict=feed_dict)

In [10]:
with tf.Session() as sess:
    
    init.run()
    
    feed_dict = {x: x_batch, seq_length : seq_length_batch}
    output_val, states_val = sess.run([output, states], feed_dict=feed_dict)

In [11]:
print(output.shape)
print(output_val.shape)

(?, 2, 5)
(4, 2, 5)


In [12]:
print(output_val[0]) # instance 0

[[-0.2222962  -0.705766   -0.79374397  0.09923602  0.13796386]
 [ 0.99216175 -0.99974066 -1.          0.19720669  0.32353416]]


In [13]:
print(output_val[1]) # instance 1

[[ 0.6322138  -0.990431   -0.99992096  0.4300523   0.3162347 ]
 [ 0.          0.          0.          0.          0.        ]]


In [14]:
print(output_val[2]) # instance 2

[[ 0.9374113  -0.9997321  -1.          0.6752648   0.4746584 ]
 [ 0.993002   -0.9973043  -0.999934    0.37843975  0.26146594]]


In [15]:
print(output_val[3]) # instance 3

[[ 0.97622555 -0.30857518 -0.99983215 -0.14541316  0.9705903 ]
 [ 0.97007096 -0.6166968  -0.9446136  -0.42038926 -0.14164537]]


In [16]:
print(states_val) # final states

[[ 0.99216175 -0.99974066 -1.          0.19720669  0.32353416]
 [ 0.6322138  -0.990431   -0.99992096  0.4300523   0.3162347 ]
 [ 0.993002   -0.9973043  -0.999934    0.37843975  0.26146594]
 [ 0.97007096 -0.6166968  -0.9446136  -0.42038926 -0.14164537]]
