In [1]:
import tensorflow as tf
import numpy as np
tf.reset_default_graph()
tf.set_random_seed(0)
np.random.seed(0)

In [2]:
n_inputs = 2
n_hidden1 = 3

In [3]:
original_w = [[1., 2., 3.], [4., 5., 6.]] # Load the weights from the other framework
original_b = [7., 8., 9.]                 # Load the biases from the other framework

In [4]:
x = tf.placeholder(tf.float32, shape=(None, n_inputs), name="x")
hidden1 = tf.layers.dense(x, n_hidden1, activation=tf.nn.relu, name="hidden1")
# [...] Build the rest of the model

Instructions for updating:
Use keras.layers.Dense instead.
Instructions for updating:
Please use `layer.__call__` method instead.


In [5]:
tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES)

[<tf.Variable 'hidden1/kernel:0' shape=(2, 3) dtype=float32_ref>,
 <tf.Variable 'hidden1/bias:0' shape=(3,) dtype=float32_ref>]

In [6]:
# Get a handle on the assignment nodes for the hidden1 variables
g = tf.get_default_graph()
w1 = g.get_tensor_by_name('hidden1/kernel:0')
b1 = g.get_tensor_by_name('hidden1/bias:0')
assign_kernel = g.get_operation_by_name("hidden1/kernel/Assign")
assign_bias = g.get_operation_by_name("hidden1/bias/Assign")
init_kernel = assign_kernel.inputs[1]
init_bias = assign_bias.inputs[1]

In [7]:
for i in assign_kernel.inputs:
    print(i)

Tensor("hidden1/kernel:0", shape=(2, 3), dtype=float32_ref)
Tensor("hidden1/kernel/Initializer/random_uniform:0", shape=(2, 3), dtype=float32)


In [8]:
for i in assign_bias.inputs:
    print(i)

Tensor("hidden1/bias:0", shape=(3,), dtype=float32_ref)
Tensor("hidden1/bias/Initializer/zeros:0", shape=(3,), dtype=float32)


In [9]:
init = tf.global_variables_initializer()

In [11]:
with tf.Session() as sess:
    sess.run(init, feed_dict={init_kernel: original_w, init_bias: original_b})
    w1_run, b1_run = sess.run([w1, b1])
    print(w1_run)
    print(b1_run)

[[1. 2. 3.]
 [4. 5. 6.]]
[7. 8. 9.]
