In [1]:
# import numpy as np

# # t = 0
# # batch_size = 4
# # n_features = 3
# x_0_batch = np.array(
#     [[0, 1, 2], 
#      [3, 4, 5], 
#      [6, 7, 8], 
#      [9, 0, 1]]) 

In [2]:
# # t = 1
# # batch_size = 4
# # n_features = 3
# x_1_batch = np.array(
#     [[9, 8, 7], 
#      [0, 0, 0], 
#      [6, 5, 4], 
#      [3, 2, 1]]) 

In [3]:
import numpy as np

x_batch = np.array([
    # t  =  0 ,  t  =  1
    [[0, 1, 2], [9, 8, 7]], # instance 0
    [[3, 4, 5], [0, 0, 0]], # instance 1
    [[6, 7, 8], [6, 5, 4]], # instance 2
    [[9, 0, 1], [3, 2, 1]], # instance 3
])

In [4]:
import tensorflow as tf
import numpy as np
tf.reset_default_graph()
tf.set_random_seed(0)
np.random.seed(0)

In [5]:
# for a time series data of batch_size = 1
# at each time t
# observation.shape = (n_inputs,)
n_inputs = 3

In [6]:
# internally current state is represented by neurons 
# n_neurons.shape = (n_neurons,)
n_neurons = 5

In [7]:
# # placehoder to feed batch data of time 0
# x_0 = tf.placeholder(tf.float32, [None, n_inputs])

In [8]:
# # placehoder to feed batch data of time 1
# x_1 = tf.placeholder(tf.float32, [None, n_inputs])

In [9]:
# x_0 ---> x_list[0]
# x_1 ---> x_list[1]
n_steps = 2
x = tf.placeholder(tf.float32, [None, n_steps, n_inputs]) # (?, 2, 3)
xt = tf.transpose(x, perm=[1, 0, 2]) # (2, ?, 3)
x_list = tf.unstack(xt) # Python list of tensors
print(x.shape, xt.shape, x_list[0].shape, x_list[1].shape)

(?, 2, 3) (2, ?, 3) (?, 3) (?, 3)


In [10]:
# # a factory that creates copies of the cell to build the unrolled RNN
# basic_cell = tf.nn.rnn_cell.BasicRNNCell(num_units=n_neurons)

# # output_seqs: a Python list containing the output tensors for each time step.
# # states: a tensor containing the final states of the network.
# output, states = tf.nn.static_rnn(
#     basic_cell, [x_0, x_1], dtype=tf.float32)

In [11]:
# a factory that creates copies of the cell to build the unrolled RNN
basic_cell = tf.nn.rnn_cell.BasicRNNCell(num_units=n_neurons)

# output_seqs: a Python list containing the output tensors for each time step.
# states: a tensor containing the final states of the network.
output, states = tf.nn.static_rnn(basic_cell, x_list, dtype=tf.float32)

Instructions for updating:
This class is equivalent as tf.keras.layers.SimpleRNNCell, and will be replaced by that in Tensorflow 2.0.
Instructions for updating:
Please use `keras.layers.RNN(cell, unroll=True)`, which is equivalent to this API
Instructions for updating:
Please use `layer.add_weight` method instead.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [12]:
init = tf.global_variables_initializer()

In [13]:
# with tf.Session() as sess:
    
#     init.run()
    
#     feed_dict = {x_0: x_0_batch, x_1: x_1_batch}
#     output_val = sess.run(output, feed_dict=feed_dict)

In [14]:
with tf.Session() as sess:
    
    init.run()
    
    feed_dict = {x: x_batch}
    output_val = sess.run(output, feed_dict=feed_dict)

In [15]:
print(output_val[0]) # output at t = 0

[[ 0.8873027   0.21025889 -0.14533019 -0.48752266  0.85590076]
 [ 0.99843115  0.98781997  0.92071897 -0.9943569   0.99720544]
 [ 0.9999795   0.99988496  0.9974604  -0.99995345  0.9999496 ]
 [-0.22379977  0.9999663   0.99581414 -0.9978002   0.48085815]]


In [16]:
print(output_val[1]) # output at t = 1

[[ 0.999987    0.9999994   0.9999013  -0.99999803  0.9998745 ]
 [ 0.63951737  0.55478317 -0.12084428 -0.6423976   0.1832351 ]
 [ 0.99862087  0.99991626  0.99832207 -0.9999157   0.9939804 ]
 [ 0.62831557  0.98743516  0.9772627  -0.9941337   0.91406375]]
