In [1]:
import numpy as np

x_batch = np.array([
    # t  =  0 ,  t  =  1
    [[0, 1, 2], [9, 8, 7]], # instance 0
    [[3, 4, 5], [0, 0, 0]], # instance 1
    [[6, 7, 8], [6, 5, 4]], # instance 2
    [[9, 0, 1], [3, 2, 1]], # instance 3
])

In [2]:
import tensorflow as tf
import numpy as np
tf.reset_default_graph()
tf.set_random_seed(0)
np.random.seed(0)

In [3]:
# for a time series data of batch_size = 1
# at each time t
# observation.shape = (n_inputs,)
n_inputs = 3

In [4]:
# internally current state is represented by neurons 
# n_neurons.shape = (n_neurons,)
n_neurons = 5

In [5]:
n_steps = 2
x = tf.placeholder(tf.float32, [None, n_steps, n_inputs]) # (?, 2, 3)
xt = tf.transpose(x, perm=[1, 0, 2]) # (2, ?, 3)
x_list = tf.unstack(xt) # Python list of tensors

In [6]:
basic_cell = tf.nn.rnn_cell.BasicRNNCell(num_units=n_neurons)
output, states = tf.nn.static_rnn(basic_cell, x_list, dtype=tf.float32)

In [7]:
n_steps = 2
x = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
basic_cell = tf.nn.rnn_cell.BasicRNNCell(num_units=n_neurons)
output, states = tf.nn.dynamic_rnn(basic_cell, x, dtype=tf.float32)

Instructions for updating:
This class is equivalent as tf.keras.layers.SimpleRNNCell, and will be replaced by that in Tensorflow 2.0.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
Instructions for updating:
Please use `layer.add_weight` method instead.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [8]:
init = tf.global_variables_initializer()

In [9]:
with tf.Session() as sess:
    
    init.run()
    
    feed_dict = {x: x_batch}
    output_val = sess.run(output, feed_dict=feed_dict)

In [10]:
print(output.shape)
print(output_val.shape)

(?, 2, 5)
(4, 2, 5)


In [11]:
print(output_val[0]) # instance 0

[[-0.7240292   0.1729725  -0.28965423  0.45602557 -0.41152507]
 [ 0.43919027  0.08289638  0.999875    1.         -0.9958653 ]]


In [12]:
print(output_val[1]) # instance 1

[[-0.77846056  0.30244738  0.8192223   0.9992123  -0.95512027]
 [ 0.26223034 -0.2124709   0.46467596 -0.8174648   0.98172075]]


In [13]:
print(output_val[2]) # instance 2

[[-0.8232567   0.4216468   0.9891809   0.99999917 -0.9974753 ]
 [ 0.7244756  -0.0920199   0.9988207   0.9999226   0.09839412]]


In [14]:
print(output_val[3]) # instance 3

[[ 0.9117618   0.1921009   0.9793051   0.9999879  -0.9991379 ]
 [ 0.9271179   0.04543867  0.98198324  0.9893481   0.4947898 ]]


In [20]:
import scipy.special as special
a = special.softmax(np.array([[0,1,2,3,4,5,6,7,5.5,4.3],[0,1,2,3,4,3.1,2.6,1.7,0.8,-0.9]]), axis=1)
print(np.round(a,2))

[[0.   0.   0.   0.01 0.03 0.07 0.2  0.53 0.12 0.04]
 [0.01 0.02 0.06 0.16 0.42 0.17 0.1  0.04 0.02 0.  ]]
